Foreground yes
TCPSocket 3310
TCPAddr 0.0.0.0
DatabaseDirectory /var/lib/clamav
PidFile /tmp/clamd.pid
LogTime yes
MaxScanSize 6M
MaxFileSize 5M
StreamMaxLength 5M
ReadTimeout 30
CommandReadTimeout 5
MaxThreads 2
SelfCheck 60
