import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — Family Documents",
  description: "How Family Documents collects, uses, stores and protects personal information, including Google Drive data.",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPolicy() {
  return <main className="legal-page">
    <nav className="legal-nav"><Link className="wordmark" href="/"><span>FD</span>Family Documents</Link><a href="/app/">Sign in</a></nav>
    <article className="legal-document">
      <header><p className="eyebrow">Your information, explained clearly</p><h1>Privacy Policy</h1><p className="legal-updated">Last updated 20 September 2026</p><p>This policy explains what Family Documents collects, why we use it, where it may be processed, and the choices available to you. Family Documents is an early-access service operated from New Zealand. Contact us at <a href="mailto:contact@familydocuments.app">contact@familydocuments.app</a>.</p></header>
      <section><h2>1. Information we collect</h2><p>We collect only information needed to provide the service you choose to use:</p><ul><li><strong>Account information</strong>, such as your email address, display name, authentication records and household role.</li><li><strong>Family workspace information</strong>, including invited members, categories, sharing choices and access audit records.</li><li><strong>Content you add</strong>, such as document files and metadata, reminders, forwarded emails and attachments, saved links, rental-property details and bill records.</li><li><strong>Technical and security information</strong>, including timestamps, file size and hashes, provider identifiers, error codes and security events needed to operate and protect the service.</li></ul><p>Please avoid adding information that is unnecessary for your family workspace. Do not upload real documents during synthetic or test-only stages identified in the product.</p></section>
      <section><h2>2. How we use information</h2><p>We use information to authenticate users, organise and retrieve family records, apply your sharing choices, process optional OCR, suggest categories or dates for your confirmation, deliver reminders, receive documents you forward by email, maintain security and troubleshoot the service.</p><p>We do not sell personal information. We do not use document contents or Google user data for advertising. AI-generated suggestions do not become confirmed records until a user approves them.</p></section>
      <section><h2>3. Google Drive data</h2><p>Connecting Google Drive is optional. Family Documents requests the narrow <code>drive.file</code> permission, which covers files and folders you explicitly select or create for use with the app. It does not request permission to scan or list your whole Drive.</p><ul><li>Original documents saved through the app are kept in the family-selected Google Drive folder and its app-created subfolders.</li><li>We store an encrypted Google refresh credential on the Family Documents service so authorised app actions can upload and reopen those originals without asking you to reconnect each time. We never receive or store your Google password.</li><li>We retain folder and file identifiers plus limited metadata needed to organise, upload, reopen and detect changes, such as name, type, size, version, modified time and checksums.</li><li>Document bytes pass through the secured Family Documents gateway when you upload, preview or process a file. Temporary processing copies are used only as needed for the requested action.</li><li>Disconnecting revokes future app access and does not delete originals from Google Drive.</li></ul><p>Family Documents&apos; use and transfer of information received from Google APIs will comply with the <a href="https://developers.google.com/terms/api-services-user-data-policy" target="_blank" rel="noopener noreferrer">Google API Services User Data Policy</a>, including its Limited Use requirements.</p></section>
      <section><h2>4. Storage and service providers</h2><p>Google Drive is the source of truth for original documents saved through the current app. The privately operated Family Documents service stores the metadata and derived information needed to organise and use them, including categories, tags, relationships, permissions, reminders, search indexes and optional extracted text. Forwarded email and attachments may be staged while they are security-checked, reviewed and saved. Some older records may still use legacy service-held source storage while migration work is completed.</p><p>Website delivery, security and inbound-email routing use Cloudflare. Outbound account and reminder email uses an email delivery provider. Google processes Drive originals under your Google account and Google&apos;s terms. Some providers may process information outside New Zealand; laws in another country may differ.</p></section>
      <section><h2>5. Sharing and disclosure</h2><p>Confirmed Library records are available to active members of the relevant family workspace. Supported personal items, including Saved Links, can remain private or be shared with named family members. Household administrators may have the management access described in the app. We may disclose information to service providers acting for us, when you direct us to, to protect the service or a person, or when required by law. Providers receive only the information needed for their function.</p></section>
      <section><h2>6. Security</h2><p>We use access controls, isolated application storage, encrypted web connections, short-lived sessions, malware scanning, audit records and multi-factor checks for high-risk actions. No system is completely secure. Keep your account credentials private, use multi-factor authentication when offered, and tell us promptly if you suspect unauthorised access.</p></section>
      <section><h2>7. Retention and deletion</h2><p>We keep information while your account or workspace needs it and for bounded security, recovery and legal purposes. Some deletion actions are recoverable for a limited period before permanent removal; backup copies age out through the backup cycle. Google originals remain in Google Drive until you delete them there. You can request account deletion from Profile in the app or follow the steps on our <a href="/account-deletion">account-deletion page</a>.</p></section>
      <section><h2>8. Access, correction and choices</h2><p>You can view and update much of your information in the app, change sharing, disconnect Google Drive and delete supported records. You may ask us for access to, or correction of, personal information we hold about you. You may also raise a privacy concern with us or contact the <a href="https://www.privacy.org.nz/" target="_blank" rel="noopener noreferrer">New Zealand Office of the Privacy Commissioner</a>.</p></section>
      <section><h2>9. Children and family information</h2><p>The service is intended to be administered by adults. A parent or guardian should decide what information about a child is appropriate to add and who may access it.</p></section>
      <section><h2>10. Changes to this policy</h2><p>We will update this page when our practices materially change. If a change affects how we use Google user data or other important personal information, we will provide an appropriate notice and seek consent where required.</p></section>
    </article>
    <footer className="legal-footer"><Link href="/">Home</Link><a href="/terms">Terms of Service</a><a href="mailto:contact@familydocuments.app">Contact</a></footer>
  </main>;
}
