begin;

do $$
declare
  owner_id constant uuid:='29000000-0000-4000-8000-000000000001';
  other_id constant uuid:='29000000-0000-4000-8000-000000000002';
  family_one constant uuid:='29000000-0000-4000-8000-000000000011';
  family_two constant uuid:='29000000-0000-4000-8000-000000000012';
  conversation_id uuid; link_id uuid; callback_nonce text; old_callback_nonce text; update_record_id uuid; attachment_id uuid; staged_attachment_id uuid:=gen_random_uuid(); lease uuid; result jsonb;
begin
  if has_function_privilege('authenticated','fp.ingest_telegram_update(text,bigint,text,text,text,jsonb)','execute')
    or has_function_privilege('authenticated','fp.consume_telegram_link_token(text,text,text,text,jsonb)','execute')
    or has_function_privilege('anon','fp.telegram_connection_status()','execute') then
    raise exception 'transport service boundary is exposed';
  end if;
  insert into fp.households(id,name,owner_user_id) values(family_one,'Telegram Family',owner_id),(family_two,'Other Family',other_id);
  insert into fp.members(household_id,user_id,email,role) values(family_one,owner_id,'telegram-owner@example.test','owner'),(family_two,other_id,'telegram-other@example.test','owner');
  insert into fp.categories(household_id,name,created_by) values(family_one,'Rentals',owner_id),(family_one,'Finance',owner_id);
  insert into fp.saved_link_categories(household_id,owner_user_id,name) values(family_one,owner_id,'Travel');
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'email','telegram-owner@example.test','role','authenticated')::text,true);
  result:=fp.create_telegram_link_token(family_one,'test-bot',repeat('a',64));
  if result->>'expires_at' is null then raise exception 'link token was not created';end if;
  perform set_config('request.jwt.claims','{"role":"service_role"}',true);
  result:=fp.consume_telegram_link_token('test-bot',repeat('a',64),'123456','123456','{"display_name":"Synthetic"}');
  link_id:=(result->>'identity_link_id')::uuid;
  begin perform fp.consume_telegram_link_token('test-bot',repeat('a',64),'123456','123456','{}');raise exception 'link token replay succeeded';exception when sqlstate 'PT410' then null;end;
  result:=fp.telegram_transport_context('test-bot','123456','123456');
  if (result->>'linked')::boolean is not true or (result->>'family_id')::uuid<>family_one then raise exception 'numeric identity did not bind to Family';end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'email','telegram-owner@example.test','role','authenticated','family_id',family_one)::text,true);
  if fp.active_family_id()<>family_one then raise exception 'request-scoped Family was not selected';end if;
  conversation_id:=(fp.start_conversation('telegram-conversation-0001')->>'id')::uuid;
  perform set_config('request.jwt.claims','{"role":"service_role"}',true);
  perform fp.bind_telegram_conversation('test-bot','123456','123456',conversation_id);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'email','telegram-owner@example.test','role','authenticated','family_id',family_one)::text,true);
  result:=fp.submit_conversation_action(conversation_id,'telegram-clarification-0001','request_clarification',1,'{"question":"Which category?","missing_parameter":"category"}'::jsonb,'telegram-cancel-request-0001',false);
  perform set_config('request.jwt.claims','{"role":"service_role"}',true);
  result:=fp.telegram_cancel_pending('test-bot','123456','123456');
  if (result->>'cancelled')::boolean is not true then raise exception '/cancel did not cancel pending clarification';end if;
  result:=fp.telegram_cancel_pending('test-bot','123456','123456');
  if (result->>'cancelled')::boolean is true then raise exception '/cancel was not idempotent';end if;
  result:=fp.telegram_family_choices('test-bot','123456','123456');
  if (result->>'only_one')::boolean is not true then raise exception '/family did not explain the single-Family case';end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'email','telegram-owner@example.test','role','authenticated','family_id',family_one)::text,true);
  result:=fp.submit_conversation_action(conversation_id,'telegram-clarification-0002','request_clarification',1,jsonb_build_object('question','Which category?','missing_parameter','category_name','attachment_id','29000000-0000-4000-8000-000000000077','tags','[]'::jsonb),'telegram-category-request-0001',false);
  perform set_config('request.jwt.claims','{"role":"service_role"}',true);
  result:=fp.prepare_telegram_category_clarification(link_id,(result->>'execution_id')::uuid);
  if jsonb_array_length(result->'choices')<2 or not result->'choices' ? 'Rentals' or not result->'choices' ? 'Finance' then raise exception 'category clarification did not expose authorised choices';end if;
  callback_nonce:=(fp.create_telegram_callback(link_id,conversation_id,'clarification',(select id from fp.conversation_executions where action_id='telegram-clarification-0002'),result->'choice_actions'->0->>'id')->>'nonce');
  perform fp.telegram_cancel_pending('test-bot','123456','123456');
  begin perform fp.consume_telegram_callback('test-bot','123456','123456',callback_nonce);raise exception 'cancelled clarification callback remained active';exception when sqlstate 'PT410' then null;end;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'email','telegram-owner@example.test','role','authenticated','family_id',family_one)::text,true);
  result:=fp.submit_conversation_action(conversation_id,'telegram-link-question-0001','request_clarification',1,jsonb_build_object('question','Which category?','missing_parameter','category_name','link_url','https://example.net/phase2e','link_title','example.net'),'telegram-link-question-key-0001',false);
  perform set_config('request.jwt.claims','{"role":"service_role"}',true);
  result:=fp.prepare_telegram_category_clarification(link_id,(result->>'execution_id')::uuid);
  select value->>'id' into callback_nonce from jsonb_array_elements(result->'choice_actions') where lower(value->'parameters'->>'category_name')='travel';
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'email','telegram-owner@example.test','role','authenticated','family_id',family_one)::text,true);
  result:=fp.decide_conversation_clarification((select id from fp.conversation_executions where action_id='telegram-link-question-0001'), 'select', callback_nonce);
  if result->>'state'<>'awaiting_confirmation' then raise exception 'link category choice did not reach confirmation';end if;
  result:=fp.decide_conversation_confirmation((result->'confirmation'->>'id')::uuid,'confirm');
  if result->>'state'<>'succeeded' or (select count(*) from fp.saved_links where source_host='example.net')<>1 then raise exception 'multi-turn Telegram link save did not complete exactly once';end if;
  perform set_config('request.jwt.claims','{"role":"service_role"}',true);
  result:=fp.create_telegram_callback(link_id,conversation_id,'confirmation','29000000-0000-4000-8000-000000000099','confirm');
  callback_nonce:=result->>'nonce';
  begin perform fp.consume_telegram_callback('test-bot','999999','999999',callback_nonce);raise exception 'wrong Telegram user consumed callback';exception when sqlstate 'PT410' then null;end;
  result:=fp.consume_telegram_callback('test-bot','123456','123456',callback_nonce);
  if result->>'value'<>'confirm' then raise exception 'bound callback was not returned';end if;
  begin perform fp.consume_telegram_callback('test-bot','123456','123456',callback_nonce);raise exception 'callback replay succeeded';exception when sqlstate 'PT410' then null;end;
  result:=fp.create_telegram_callback(link_id,conversation_id,'cancel',null,'cancel');callback_nonce:=result->>'nonce';
  update fp.transport_callbacks
     set created_at=now()-interval '2 seconds',
         expires_at=now()-interval '1 second'
   where nonce_hash=encode(extensions.digest(callback_nonce,'sha256'),'hex');
  begin perform fp.consume_telegram_callback('test-bot','123456','123456',callback_nonce);raise exception 'expired callback succeeded';exception when sqlstate 'PT410' then null;end;
  result:=fp.ingest_telegram_update('test-bot',42,'123456','123456','message','{"update_id":42,"message":{"document":{"file_id":"synthetic-pdf","file_unique_id":"unique-pdf","file_name":"synthetic.pdf","mime_type":"application/pdf","file_size":12}}}');update_record_id:=(result->>'id')::uuid;
  if (result->>'duplicate')::boolean then raise exception 'new update was marked duplicate';end if;
  result:=fp.ingest_telegram_update('test-bot',42,'123456','123456','message','{"update_id":42}');
  if (result->>'duplicate')::boolean is not true or (select count(*) from fp.transport_updates where provider_update_id=42)<>1 then raise exception 'update replay was not deduplicated';end if;
  result:=fp.claim_telegram_updates('test-bot',1);lease:=(result->0->>'lease_token')::uuid;
  result:=fp.claim_telegram_attachment(update_record_id,lease);
  if result->>'file_unique_id'<>'unique-pdf' or result->>'state'<>'downloading' then raise exception 'durable attachment was not claimed';end if;
  attachment_id:=(result->>'id')::uuid;
  result:=fp.stage_telegram_attachment(attachment_id,lease,'application/pdf',12,repeat('b',64),attachment_id||'.pdf');
  if not fp.finish_telegram_attachment(attachment_id,lease,staged_attachment_id) then raise exception 'attachment was not completed';end if;
  if (select conversation_attachment_id from fp.transport_attachments where id=attachment_id) is distinct from staged_attachment_id then raise exception 'staged conversation attachment was not retained';end if;
  result:=fp.create_telegram_review(update_record_id,attachment_id,'attachment_needs_decision');
  if (select count(*) from fp.transport_inbox_items i where i.update_id=update_record_id)<>1 then raise exception 'Telegram review item was not deduplicated';end if;
  perform fp.create_telegram_review(update_record_id,attachment_id,'attachment_needs_decision');
  if (select count(*) from fp.transport_inbox_items i where i.update_id=update_record_id)<>1 then raise exception 'Telegram review replay duplicated Inbox item';end if;
  if not fp.resolve_telegram_review(link_id,staged_attachment_id) then raise exception 'completed command did not resolve its Telegram review';end if;
  if (select review_state from fp.transport_inbox_items i where i.update_id=update_record_id)<>'reviewed' then raise exception 'completed command remained in the unreviewed Telegram Inbox';end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'email','telegram-owner@example.test','role','authenticated','family_id',family_one)::text,true);
  result:=fp.telegram_inbox_workspace(null,'all',30,0);
  if result->'items'->0->>'source'<>'Telegram' then raise exception 'Telegram Inbox source metadata was not explicit';end if;
  result:=fp.telegram_inbox_message_detail((result->'items'->0->>'id')::uuid);
  if result->>'source'<>'Telegram' or result ? 'envelope' then raise exception 'Telegram Inbox detail was unsafe';end if;
  perform set_config('request.jwt.claims','{"role":"service_role"}',true);
  perform fp.complete_telegram_update(update_record_id,lease,'handled','[{"request_key":"telegram:42:reply","text":"Done"}]');
  if (select count(*) from fp.transport_outbox where request_key='telegram:42:reply')<>1 then raise exception 'durable outbox was not created';end if;
  if (select envelope from fp.transport_updates where id=update_record_id)<>'{}'::jsonb then raise exception 'completed payload was retained';end if;
  if (select a.state from fp.transport_attachments a where a.update_id=update_record_id)<>'completed' then raise exception 'attachment state was not durable';end if;
  insert into fp.members(household_id,user_id,email,role) values(family_two,owner_id,'telegram-owner@example.test','contributor');
  result:=fp.telegram_family_choices('test-bot','123456','123456');
  if jsonb_array_length(result->'choices')<>2 then raise exception '/family did not show authorised memberships';end if;
  select value->>'nonce' into callback_nonce from jsonb_array_elements(result->'choices') where value->>'label'='Other Family';
  select value->>'nonce' into old_callback_nonce from jsonb_array_elements(result->'choices') where value->>'label' like 'Telegram Family%';
  update fp.members set status='suspended' where household_id=family_two and user_id=owner_id;
  begin perform fp.apply_telegram_control_callback('test-bot','123456','123456',callback_nonce);raise exception 'revoked Family selection succeeded';exception when sqlstate '42501' then null;end;
  update fp.members set status='active' where household_id=family_two and user_id=owner_id;
  result:=fp.apply_telegram_control_callback('test-bot','123456','123456',callback_nonce);
  if (result->>'family_id')::uuid<>family_two then raise exception 'Family callback did not switch Family';end if;
  begin perform fp.apply_telegram_control_callback('test-bot','123456','123456',callback_nonce);raise exception 'Family callback replay succeeded';exception when sqlstate 'PT410' then null;end;
  begin perform fp.apply_telegram_control_callback('test-bot','123456','123456',old_callback_nonce);raise exception 'Family switch left an old callback active';exception when sqlstate 'PT410' then null;end;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'email','telegram-owner@example.test','role','authenticated','family_id',family_two)::text,true);
  conversation_id:=(fp.start_conversation('telegram-conversation-0002')->>'id')::uuid;
  perform set_config('request.jwt.claims','{"role":"service_role"}',true);
  perform fp.bind_telegram_conversation('test-bot','123456','123456',conversation_id);
  result:=fp.telegram_family_choices('test-bot','123456','123456');
  select value->>'nonce' into callback_nonce from jsonb_array_elements(result->'choices') where value->>'label'='Telegram Family';
  perform fp.apply_telegram_control_callback('test-bot','123456','123456',callback_nonce);
  perform set_config('request.jwt.claims','{"role":"service_role"}',true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'email','telegram-owner@example.test','role','authenticated','family_id',family_one)::text,true);
  conversation_id:=(fp.start_conversation('telegram-conversation-0003')->>'id')::uuid;
  perform set_config('request.jwt.claims','{"role":"service_role"}',true);
  perform fp.bind_telegram_conversation('test-bot','123456','123456',conversation_id);
  result:=fp.create_telegram_callback(link_id,conversation_id,'cancel',null,'cancel');
  perform fp.apply_telegram_control_callback('test-bot','123456','123456',result->>'nonce');
  if not (fp.telegram_transport_context('test-bot','123456','123456')->>'linked')::boolean then raise exception 'disconnect cancellation revoked the link';end if;
  result:=fp.create_telegram_callback(link_id,conversation_id,'disconnect',null,'confirm');callback_nonce:=result->>'nonce';
  result:=fp.apply_telegram_control_callback('test-bot','123456','123456',callback_nonce);
  if (result->>'disconnected')::boolean is not true then raise exception 'Telegram disconnect was not confirmed';end if;
  if (fp.telegram_transport_context('test-bot','123456','123456')->>'linked')::boolean then raise exception 'disconnect did not revoke link';end if;
  begin perform fp.apply_telegram_control_callback('test-bot','123456','123456',callback_nonce);raise exception 'disconnect callback replay succeeded';exception when sqlstate 'PT410' then null;end;
end$$;

rollback;
