do $$
declare owner_id uuid:=gen_random_uuid();admin_id uuid:=gen_random_uuid();viewer_id uuid:=gen_random_uuid();outsider_id uuid:=gen_random_uuid();hid uuid:=gen_random_uuid();other_hid uuid:=gen_random_uuid();category_id uuid;created_link_id uuid;result jsonb;duplicate jsonb;
begin
  insert into fp.households(id,name,owner_user_id) values(hid,'Synthetic Saved Links household',owner_id),(other_hid,'Synthetic outsider household',outsider_id);
  insert into fp.members(household_id,user_id,email,display_name,role) values(hid,owner_id,'links-owner@example.test','Link Owner','owner'),(hid,admin_id,'links-admin@example.test','Family Admin','family_admin'),(hid,viewer_id,'links-viewer@example.test','Link Viewer','viewer'),(other_hid,outsider_id,'links-outsider@example.test','Outsider','owner');
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'email','links-owner@example.test')::text,true);perform fp.ensure_saved_link_defaults();select id into category_id from fp.saved_link_categories where owner_user_id=owner_id and system_key='watch_later';
  result:=fp.create_saved_link_category('Garden');if result->>'name'<>'Garden' then raise exception 'personal category creation failed';end if;
  result:=fp.create_saved_link('https://www.instagram.com/reel/SYNTHETIC/?utm_source=copy_link#fragment','Synthetic Reel','No real content',category_id);created_link_id:=(result->>'id')::uuid;if result->>'private'<>'true' or exists(select 1 from fp.saved_link_permissions p where p.link_id=created_link_id) then raise exception 'creation was not private';end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',admin_id,'email','links-admin@example.test')::text,true);perform fp.ensure_saved_link_defaults();if jsonb_array_length(fp.saved_link_workspace()->'links')<>0 then raise exception 'household admin saw private link';end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',viewer_id,'email','links-viewer@example.test')::text,true);perform fp.ensure_saved_link_defaults();if jsonb_array_length(fp.saved_link_workspace()->'links')<>0 then raise exception 'viewer saw private link';end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',outsider_id,'email','links-outsider@example.test')::text,true);perform fp.ensure_saved_link_defaults();if jsonb_array_length(fp.saved_link_workspace()->'links')<>0 then raise exception 'outsider saw private link';end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'email','links-owner@example.test')::text,true);perform fp.set_saved_link_shares(created_link_id,array[viewer_id]);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',viewer_id,'email','links-viewer@example.test')::text,true);result:=fp.saved_link_workspace();if jsonb_array_length(result->'links')<>1 or jsonb_array_length(result->'links'->0->'shared_with')<>0 then raise exception 'recipient read or recipient-list minimisation failed';end if;
  begin perform fp.update_saved_link(created_link_id,'Changed by recipient',null,(select id from fp.saved_link_categories where owner_user_id=viewer_id limit 1));raise exception 'recipient updated shared link';exception when no_data_found then null;end;
  begin perform fp.set_saved_link_shares(created_link_id,array[admin_id]);raise exception 'recipient reshared link';exception when no_data_found then null;end;
  begin perform fp.delete_saved_link(created_link_id);raise exception 'recipient deleted link';exception when no_data_found then null;end;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'email','links-owner@example.test')::text,true);perform fp.set_saved_link_shares(created_link_id,'{}'::uuid[]);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',viewer_id,'email','links-viewer@example.test')::text,true);if jsonb_array_length(fp.saved_link_workspace()->'links')<>0 then raise exception 'unshare did not revoke immediately';end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'email','links-owner@example.test')::text,true);perform fp.set_saved_link_shares(created_link_id,array[viewer_id]);update fp.members set status='suspended' where household_id=hid and user_id=viewer_id;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',viewer_id,'email','links-viewer@example.test')::text,true);if jsonb_array_length(fp.saved_link_workspace()->'links')<>0 then raise exception 'suspension did not revoke access';end if;update fp.members set status='active' where household_id=hid and user_id=viewer_id;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'email','links-owner@example.test')::text,true);duplicate:=fp.create_saved_link('https://www.instagram.com/reel/SYNTHETIC/?utm_source=copy_link#different','Duplicate synthetic Reel',null,category_id);if duplicate->>'duplicate_of'<>created_link_id::text then raise exception 'owner duplicate detection failed';end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',admin_id,'email','links-admin@example.test')::text,true);select id into category_id from fp.saved_link_categories where owner_user_id=admin_id and system_key='watch_later';duplicate:=fp.create_saved_link('https://www.instagram.com/reel/SYNTHETIC/?utm_source=copy_link','Admin copy',null,category_id);if duplicate->>'duplicate_of' is not null then raise exception 'duplicate leaked across owners';end if;
  begin perform fp.create_saved_link('http://example.com/not-https','Bad scheme',null,category_id);raise exception 'HTTP URL accepted';exception when invalid_parameter_value then null;end;
  begin perform fp.create_saved_link('https://user:pass@example.com/private','Credentials',null,category_id);raise exception 'credential URL accepted';exception when invalid_parameter_value then null;end;
  begin perform fp.create_saved_link('https://127.0.0.1/private','Private IP',null,category_id);raise exception 'IP URL accepted';exception when invalid_parameter_value then null;end;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'email','links-owner@example.test')::text,true);perform fp.delete_saved_link(created_link_id);if jsonb_array_length(fp.saved_link_workspace()->'links')<>1 then raise exception 'deleted link remained visible or duplicate missing';end if;perform fp.restore_saved_link(created_link_id);if jsonb_array_length(fp.saved_link_workspace()->'links')<>2 then raise exception 'restore failed';end if;
  if exists(select 1 from fp.saved_link_security_events e where e.household_id=hid and to_jsonb(e)::text ~* 'instagram|reel|synthetic content') then raise exception 'audit event contains content';end if;
end $$;
