begin;
alter table fp.email_classification_proposals add column if not exists invoice_number text check(invoice_number is null or char_length(invoice_number)<=100);
alter table fp.email_classification_proposals add column if not exists suggested_description text check(suggested_description is null or char_length(suggested_description)<=500);
alter table fp.email_classification_proposals add column if not exists suggested_record_kind text check(suggested_record_kind is null or suggested_record_kind in ('general','rental','financial_statement'));
alter table fp.email_classification_proposals add column if not exists suggested_expense_category text check(suggested_expense_category is null or suggested_expense_category in ('rates','insurance','interest','repairs','maintenance','utilities','professional_fees','compliance','other'));
alter table fp.rental_bills add column if not exists record_purpose text not null default 'general_record' check(record_purpose in ('payment','tax_support','general_record','financial_statement','other'));
alter table fp.rental_bills add column if not exists invoice_number text check(invoice_number is null or char_length(invoice_number)<=100);
alter table fp.rental_bills add column if not exists record_description text check(record_description is null or char_length(record_description)<=500);

create or replace function fp.store_classification_enrichment(proposal uuid,invoice text,description text,record_kind text,expense_category text) returns void language plpgsql security definer set search_path=pg_catalog,fp as $$ begin
  if coalesce(nullif(current_setting('request.jwt.claim.role',true),''),(nullif(current_setting('request.jwt.claims',true),'')::jsonb->>'role'),'')<>'service_role' then raise exception 'not authorised' using errcode='42501';end if;
  if record_kind not in ('general','rental','financial_statement') or expense_category not in ('rates','insurance','interest','repairs','maintenance','utilities','professional_fees','compliance','other') then raise exception 'invalid enrichment' using errcode='22023';end if;
  update fp.email_classification_proposals set invoice_number=nullif(left(trim(invoice),100),''),suggested_description=nullif(left(trim(description),500),''),suggested_record_kind=record_kind,suggested_expense_category=expense_category where id=proposal and status='needs_review';if not found then raise exception 'proposal unavailable' using errcode='P0002';end if;
end $$;

create or replace function fp.email_classification_summaries() returns jsonb language plpgsql security definer set search_path=pg_catalog,fp as $$ declare uid uuid:=fp.current_user_id();hid uuid;begin
  select household_id into hid from fp.members where user_id=uid and status='active' order by joined_at limit 1;if hid is null or not fp.is_household_admin(hid) then raise exception 'not authorised' using errcode='42501';end if;
  return coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'email_id',p.inbound_email_id,'email_subject',e.subject,'sender_address',e.sender_address,'file_name',a.file_name,'category_name',p.category_name,'title',p.title,'document_type',p.document_type,'provider_name',p.provider_name,'document_date',p.document_date,'due_date',p.due_date,'due_time',p.due_time,'due_time_zone',p.due_time_zone,'amount',p.amount,'currency',p.currency,'invoice_number',p.invoice_number,'suggested_description',p.suggested_description,'suggested_record_kind',p.suggested_record_kind,'suggested_expense_category',p.suggested_expense_category,'tags',p.tags,'confidence',p.confidence,'evidence_excerpt',p.evidence_excerpt,'source_sha256',p.source_sha256,'model_name',p.model_name,'status',p.status,'created_at',p.created_at) order by p.created_at desc) from fp.email_classification_proposals p join fp.inbound_emails e on e.id=p.inbound_email_id left join fp.inbound_attachments a on a.id=p.source_attachment_id where p.household_id=hid),'[]'::jsonb);
end $$;

create or replace function fp.create_rental_record(property uuid,document uuid,category text,purpose text,description text default null,invoice text default null,bill_amount numeric default null,bill_currency text default 'NZD',bill_due_date date default null) returns jsonb language plpgsql security definer set search_path=pg_catalog,fp as $$ declare uid uuid:=fp.current_user_id();p fp.rental_properties;d fp.documents;row fp.rental_bills;begin
  select * into p from fp.rental_properties where entity_id=property;select * into d from fp.documents where id=document and lifecycle_status='active';
  if p.entity_id is null or d.id is null or p.household_id<>d.household_id or not(fp.is_household_admin(d.household_id) or d.created_by=uid or exists(select 1 from fp.document_permissions dp where dp.document_id=d.id and dp.member_user_id=uid and dp.access_level in ('contribute','manage'))) then raise exception 'not authorised' using errcode='42501';end if;
  if category not in ('rates','insurance','interest','repairs','maintenance','utilities','professional_fees','compliance','other') or purpose not in ('payment','tax_support','general_record','financial_statement','other') or bill_amount<0 or upper(coalesce(bill_currency,'NZD'))!~'^[A-Z]{3}$' then raise exception 'invalid rental record' using errcode='22023';end if;
  insert into fp.rental_bills(household_id,property_entity_id,document_id,expense_category,status,amount,currency,due_date,account_reference,suggestion_reason,confirmed_by,record_purpose,invoice_number,record_description) values(d.household_id,p.entity_id,d.id,category,case when purpose='payment' and bill_due_date is not null and bill_due_date<=current_date then 'due' else 'confirmed' end,bill_amount,upper(coalesce(bill_currency,'NZD')),bill_due_date,nullif(left(trim(invoice),100),''),'Confirmed during email review',uid,purpose,nullif(left(trim(invoice),100),''),nullif(left(trim(description),500),'')) returning * into row;
  insert into fp.document_entities(document_id,entity_id,relationship,linked_by) values(d.id,p.entity_id,'related',uid) on conflict do nothing;return jsonb_build_object('id',row.id,'status',row.status,'property_id',row.property_entity_id,'document_id',row.document_id,'purpose',row.record_purpose);
end $$;

create or replace function fp.ensure_rental_records_category() returns trigger language plpgsql security definer set search_path=pg_catalog,fp as $$ begin insert into fp.categories(household_id,name,is_system,created_by) values(new.id,'Rental records',true,new.owner_user_id) on conflict do nothing;return new;end $$;
drop trigger if exists household_adds_rental_records_category on fp.households;create trigger household_adds_rental_records_category after insert on fp.households for each row execute function fp.ensure_rental_records_category();
insert into fp.categories(household_id,name,is_system,created_by) select h.id,'Rental records',true,h.owner_user_id from fp.households h on conflict do nothing;
revoke execute on function fp.store_classification_enrichment(uuid,text,text,text,text),fp.ensure_rental_records_category() from public,anon,authenticated;grant execute on function fp.store_classification_enrichment(uuid,text,text,text,text) to service_role;
revoke execute on function fp.email_classification_summaries(),fp.create_rental_record(uuid,uuid,text,text,text,text,numeric,text,date) from public,anon;grant execute on function fp.email_classification_summaries(),fp.create_rental_record(uuid,uuid,text,text,text,text,numeric,text,date) to authenticated;
commit;
