import ProductTour from "./product-tour";
import "./mobile-auth.css";
const benefits=[["One calm family space","Keep passports, policies, warranties, reminders and useful links organised without digging through chats and inboxes."],["Clear family access","Library records are available to your active family members, while supported personal items can remain private or be shared with named people."],["Originals in your Google Drive","Your family selects the Drive folder. Family Documents keeps the organisation, permissions, reminders and search information needed to run the app."]];
export default function Home(){return <main>
  <nav className="site-nav"><a className="wordmark" href="#top"><span>FD</span><b>Family Documents</b></a><div className="nav-links"><a href="#how-it-works">How it works</a><a href="/blog">Blog</a><a href="/faq">FAQ</a><a className="nav-auth nav-sign-in" href="/app/">Sign in</a><a className="button small nav-auth" href="/app/">Register free</a></div></nav>
  <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">A calmer home for family information</p><h1>Find the family document you need, <em>when you need it.</em></h1><p className="hero-lede">Organise important documents, renewal reminders and useful links in one family workspace, with original documents kept in your family&apos;s Google Drive.</p><div className="hero-actions"><a className="button" href="/app/">Start your free trial</a><a className="text-link" href="#demo">Watch how it works ↓</a></div><p className="trial-note">Free during early access · No credit card required</p></div><div className="product-window"><div className="window-bar"><i/><i/><i/><span>Family Documents</span></div><div className="preview-grid"><div className="preview-rail"><strong>FD</strong><span className="active">Overview</span><span>Documents</span><span>Saved links</span><span>Inbox</span></div><div className="preview-main"><small>GOOD MORNING</small><h2>Your family, organised.</h2><div className="metric-row"><div><b>2</b><span>Coming up</span></div><div><b>8</b><span>Documents</span></div><div><b>5</b><span>Saved links</span></div></div><div className="reminder"><span>CAR</span><div><strong>Car insurance renewal</strong><small>Due in 12 days</small></div><b>Review</b></div><div className="reminder"><span>PASS</span><div><strong>Passport expiry</strong><small>Due 14 February 2027</small></div><b>Open</b></div></div></div></div></section>
  <section className="trust-strip"><span>Your Drive originals</span><span>Built for families</span><span>Named sharing controls</span><span>Human-confirmed AI</span></section>
  <ProductTour/>
  <section className="section" id="how-it-works"><p className="eyebrow">Less searching. More certainty.</p><h2>Everything important, clearly organised.</h2><div className="benefit-grid">{benefits.map(([title,copy],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="feature-band" id="privacy"><div><p className="eyebrow">Privacy you can understand</p><h2>A shared Library with deliberate personal privacy.</h2></div><div className="privacy-list"><p><b>Family Library.</b> Confirmed Library records are available to active members of your family workspace.</p><p><b>Private where supported.</b> Personal items and Saved Links can stay private or be shared with named members.</p><p><b>No silent AI decisions.</b> Suggested dates, categories and organisation changes wait for your confirmation.</p></div></section>
  <section className="section split"><div><p className="eyebrow">From scattered to sorted</p><h2>Documents, reminders and links belong together—but never become a mess.</h2></div><div className="use-list"><span>Identity & travel</span><span>Home & property</span><span>Vehicles & insurance</span><span>Receipts & warranties</span><span>Family reminders</span><span>Private saved links</span></div></section>
  <section className="feature-band rental-marketing"><div><p className="eyebrow">Rentals inside Library</p><h2>Keep every property bill connected to its evidence.</h2><p>Organise rates, insurance, repairs, utilities and compliance records by property and financial year inside Library. See what is due, mark bills paid and prepare a clean annual summary for your accountant.</p><a className="button light" href="/app/">Open Family Documents</a></div><div className="privacy-list"><p><b>One view per property and year.</b> Bills, due dates, providers and source documents stay together in the app and Drive folder tree.</p><p><b>Smart, confirmed matching.</b> Earlier providers can suggest a property, but you approve every assignment.</p><p><b>Family workspace.</b> Active family members can find confirmed Library records without maintaining separate product areas.</p><p><b>Organisation, not tax advice.</b> Expense labels and exports help preparation; your accountant decides treatment.</p></div></section>
  <section className="cta"><p className="eyebrow">Early access</p><h2>Start building your family’s calm, searchable home.</h2><p>Try every available feature free while Family Documents is in early access.</p><a className="button light" href="/app/">Create your free family space</a><small>No credit card · Cancel anytime · Your data stays yours</small></section>
  <footer><a className="wordmark" href="#top"><span>FD</span>Family Documents</a><p>Private family information, clearly organised.</p><div><a href="/app/">Sign in</a><a href="/blog">Blog</a><a href="/faq">FAQ</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/account-deletion">Delete account</a><a href="mailto:contact@familydocuments.app">Contact</a></div><small>© 2026 Family Documents. Early access product.</small></footer>
</main>}
