import ProductTour from "./product-tour";
import "./mobile-auth.css";
const benefits=[["One calm family space","Keep passports, policies, warranties, reminders and useful links organised without digging through chats and inboxes."],["Private by default","Your documents and saved links start private. You choose exactly who in your family can see them."],["Your storage, your choice","Keep originals on your home server, with support for a family-selected Google Drive folder."]];
export default function Home(){return <main>
  <nav className="site-nav"><a className="wordmark" href="#top"><span>FD</span><b>Family Documents</b></a><div className="nav-links"><a href="#how-it-works">How it works</a><a href="#demo">Video guide</a><a href="#privacy">Privacy</a><a className="nav-auth nav-sign-in" href="/prototype/index.html#auth">Sign in</a><a className="button small nav-auth" href="/prototype/index.html#auth">Register free</a></div></nav>
  <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">A calmer home for family information</p><h1>Find the family document you need, <em>when you need it.</em></h1><p className="hero-lede">Organise important documents, renewal reminders and useful links in one private family workspace—without giving up control of your storage.</p><div className="hero-actions"><a className="button" href="/prototype/index.html#auth">Start your free trial</a><a className="text-link" href="#demo">Watch how it works ↓</a></div><p className="trial-note">Free during early access · No credit card required</p></div><div className="product-window"><div className="window-bar"><i/><i/><i/><span>Family Documents</span></div><div className="preview-grid"><div className="preview-rail"><strong>FD</strong><span className="active">Overview</span><span>Documents</span><span>Saved links</span><span>Inbox</span></div><div className="preview-main"><small>GOOD MORNING</small><h2>Your family, organised.</h2><div className="metric-row"><div><b>2</b><span>Coming up</span></div><div><b>8</b><span>Documents</span></div><div><b>5</b><span>Saved links</span></div></div><div className="reminder"><span>CAR</span><div><strong>Car insurance renewal</strong><small>Due in 12 days</small></div><b>Review</b></div><div className="reminder"><span>PASS</span><div><strong>Passport expiry</strong><small>Due 14 February 2027</small></div><b>Open</b></div></div></div></div></section>
  <section className="trust-strip"><span>Private by default</span><span>Built for families</span><span>Home-server ready</span><span>Human-confirmed AI</span></section>
  <ProductTour/>
  <section className="section" id="how-it-works"><p className="eyebrow">Less searching. More certainty.</p><h2>Everything important, clearly organised.</h2><div className="benefit-grid">{benefits.map(([title,copy],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="feature-band" id="privacy"><div><p className="eyebrow">Privacy you can understand</p><h2>Family sharing should always be a choice.</h2></div><div className="privacy-list"><p><b>Private first.</b> New documents and links are visible only to you.</p><p><b>Share with names, not vague groups.</b> Select the family members who need access.</p><p><b>No silent AI decisions.</b> Suggested dates and categories wait for your confirmation.</p></div></section>
  <section className="section split"><div><p className="eyebrow">From scattered to sorted</p><h2>Documents, reminders and links belong together—but never become a mess.</h2></div><div className="use-list"><span>Identity & travel</span><span>Home & property</span><span>Vehicles & insurance</span><span>Receipts & warranties</span><span>Family reminders</span><span>Private saved links</span></div></section>
  <section className="feature-band rental-marketing"><div><p className="eyebrow">For rental property owners</p><h2>Keep every property bill connected to its evidence.</h2><p>Organise rates, insurance, repairs, utilities and compliance records by rental property. See what is due, mark bills paid and export a clean annual summary for your accountant.</p><a className="button light" href="/prototype/index.html#rentals">Explore rental bills</a></div><div className="privacy-list"><p><b>One view per property.</b> Bills, due dates, providers and source documents stay together.</p><p><b>Smart, confirmed matching.</b> Earlier providers can suggest a property, but you approve every assignment.</p><p><b>Share deliberately.</b> Give selected family members access without exposing unrelated records.</p><p><b>Organisation, not tax advice.</b> Expense labels and exports help preparation; your accountant decides treatment.</p></div></section>
  <section className="cta"><p className="eyebrow">Early access</p><h2>Start building your family’s calm, searchable home.</h2><p>Try every available feature free while Family Documents is in early access.</p><a className="button light" href="/prototype/index.html#auth">Create your free family space</a><small>No credit card · Cancel anytime · Your data stays yours</small></section>
  <footer><a className="wordmark" href="#top"><span>FD</span>Family Documents</a><p>Private family information, clearly organised.</p><div><a href="/prototype/index.html#auth">Sign in</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="mailto:support@familydocuments.app">Contact</a></div><small>© 2026 Family Documents. Early access product.</small></footer>
</main>}
