"use client";
import {useEffect,useState} from "react";
import "./tour.css";
const steps=[
  {k:"01",title:"Create your family space",copy:"Start free, confirm your email, then name your household.",screen:<div className="tour-welcome"><span>FD</span><p>WELCOME TO FAMILY DOCUMENTS</p><h3>Create your calm family space</h3><i>Free during early access</i></div>},
  {k:"02",title:"Add a document your way",copy:"Take a photo or choose a PDF. Manual entry is the default; OCR is optional.",screen:<><div className="tour-nav">Add document</div><div className="tour-card"><b>Photo or PDF</b><span>passport-renewal.pdf</span></div><div className="tour-options"><strong>Add manually</strong><span>Use OCR</span></div></>},
  {k:"03",title:"Forward an email",copy:"Send a bill, subscription notice or attached document to your private family inbox address.",screen:<><div className="tour-nav">Household inbox</div><div className="tour-card"><b>Forward to your family address</b><span>your-family@familydocuments.app</span></div><div className="tour-private">✓ Received and security checked</div></>},
  {k:"04",title:"Review the email suggestion",copy:"The app suggests the bill name and due date. Nothing becomes a record or reminder until you confirm it.",screen:<><div className="tour-nav">Review emailed bill</div><div className="tour-review"><span>Power account · Suggested due date</span><b>28 September 2026</b><small>Human confirmation required</small></div><button>Confirm bill and reminder</button></>},
  {k:"05",title:"Choose one-off or repeating",copy:"For a subscription or regular bill, choose monthly or yearly only after checking that it really repeats.",screen:<><div className="tour-nav">Reminder schedule</div><div className="tour-options"><span>One time</span><strong>Every month</strong></div><div className="tour-card"><b>Power account</b><span>Next due 28 September · 9:00 AM</span></div></>},
  {k:"06",title:"See reminders at a glance",copy:"Upcoming renewals, bills and expiries appear on your overview when you need them.",screen:<><div className="tour-nav">Overview</div><div className="tour-metrics"><span><b>2</b>Coming up</span><span><b>8</b>Documents</span></div><div className="tour-row"><i>BILL</i><span><b>Power account</b><small>Due in 4 days · repeats monthly</small></span></div></>},
  {k:"07",title:"Save useful links privately",copy:"Paste a Reel, recipe or article. It stays private until you choose who can see it.",screen:<><div className="tour-nav">Saved links</div><div className="tour-card"><b>Weekend recipe ideas</b><span>instagram.com · Recipes</span></div><div className="tour-private">✓ Only me</div></>}
];
export default function ProductTour(){const [step,setStep]=useState(0),[playing,setPlaying]=useState(true);useEffect(()=>{if(!playing)return;const id=setInterval(()=>setStep(x=>(x+1)%steps.length),4200);return()=>clearInterval(id)},[playing]);const current=steps[step];return <section className="tour-section" id="demo"><div className="tour-heading"><div><p className="eyebrow">Guided walkthrough</p><h2>See how Family Documents works.</h2><p>A short, captioned product tour using synthetic examples—no real family data.</p></div><button className="tour-control" type="button" onClick={()=>setPlaying(!playing)}>{playing?"Ⅱ Pause":"▶ Play"}</button></div><div className="tour-stage"><div className="tour-screen" aria-live="polite"><div className="tour-browser"><i/><i/><i/><span>familydocuments.app</span></div><div className="tour-content" key={step}>{current.screen}</div></div><div className="tour-caption"><span>STEP {current.k} OF {String(steps.length).padStart(2,"0")}</span><h3>{current.title}</h3><p>{current.copy}</p><div className="tour-progress">{steps.map((x,i)=><button key={x.k} type="button" className={i===step?"active":""} onClick={()=>{setStep(i);setPlaying(false)}} aria-label={`Show step ${i+1}: ${x.title}`}/>)}</div></div></div></section>}
