/* eslint-disable @next/next/no-html-link-for-pages */
import type { Metadata } from "next";
export const metadata: Metadata = {title:"Family organisation guides | Family Documents",description:"Practical guides for organising family records, forwarded emails, renewal reminders, travel documents, and rental property evidence.",alternates:{canonical:"/blog"}};
const posts=[
  {href:"/blog/organise-family-documents",date:"8 min read",title:"How to organise family documents without creating another mess",copy:"A calm, practical system for deciding what to keep, where it belongs, and who should see it."},
  {href:"/blog/private-family-inbox",date:"6 min read",title:"Turn forwarded emails into useful family records",copy:"Keep bills, bookings, and attachments together while preserving a clear review step."},
  {href:"/blog/document-reminders",date:"7 min read",title:"A better way to track renewals and expiry dates",copy:"Separate personal reminders from household tasks and reduce last-minute surprises."},
];
export default function Blog(){return <><nav className="site-nav content-nav"><a className="wordmark" href="/"><span>FD</span><b>Family Documents</b></a><div className="nav-links"><a href="/faq">FAQ</a><a className="nav-auth nav-sign-in" href="/prototype/index.html#auth">Sign in</a><a className="button small nav-auth" href="/prototype/index.html#auth">Register free</a></div></nav><main className="content-page"><section className="content-hero"><p className="eyebrow">Practical family organisation</p><h1>Useful guides, minus the filing-cabinet fog.</h1><p>Clear advice for organising family documents, emails, reminders, travel records, and rental property evidence. Product guidance only—not legal, tax, medical, or financial advice.</p></section><section className="article-grid" aria-label="Latest guides">{posts.map(post=><a className="article-card" href={post.href} key={post.href}><small>{post.date}</small><h2>{post.title}</h2><p>{post.copy}</p><b>Read guide →</b></a>)}</section></main></>}
