const APP_URL="https://familydocuments.app/prototype/index.html#auth";

function escapeHtml(value){
  return String(value).replace(/[&<>"']/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[character]);
}

export function renderNotificationHtml(item){
  const invitation=item.kind==="invitation";
  const eyebrow=invitation?"FAMILY INVITATION":"FAMILY REMINDER";
  const heading=escapeHtml(item.subject);
  const paragraphs=String(item.body_text||"").split(/\n+/).map(line=>line.trim()).filter(Boolean).map(line=>`<p style="margin:0 0 16px;color:#4f5968;font-size:16px;line-height:1.65">${escapeHtml(line)}</p>`).join("");
  const action=invitation?`<table role="presentation" cellspacing="0" cellpadding="0" style="margin:28px 0"><tr><td style="border-radius:12px;background:#5755c9"><a href="${APP_URL}" style="display:inline-block;padding:14px 22px;color:#ffffff;font-size:16px;font-weight:700;text-decoration:none">Open Family Documents</a></td></tr></table><p style="margin:0 0 18px;color:#657083;font-size:14px;line-height:1.55">Create an account or sign in using the email address that received this invitation. The app will then show the family space waiting for you.</p>`:"";
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${heading}</title></head><body style="margin:0;padding:0;background:#f5f3ed;font-family:Arial,sans-serif;color:#17202e"><div style="display:none;max-height:0;overflow:hidden;opacity:0">${heading}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f5f3ed"><tr><td align="center" style="padding:32px 14px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:620px;overflow:hidden;border:1px solid #e1dfd8;border-radius:20px;background:#ffffff"><tr><td style="padding:24px 32px;background:#17202e"><table role="presentation" cellspacing="0" cellpadding="0"><tr><td style="width:40px;height:40px;border-radius:12px;background:#7775df;color:#ffffff;font-size:12px;font-weight:800;text-align:center">FD</td><td style="padding-left:12px;color:#ffffff;font-size:17px;font-weight:700">Family Documents</td></tr></table></td></tr><tr><td style="padding:38px 32px 30px"><p style="margin:0 0 12px;color:#5755c9;font-size:12px;font-weight:800;letter-spacing:1.5px">${eyebrow}</p><h1 style="margin:0 0 22px;color:#17202e;font-family:Georgia,serif;font-size:32px;font-weight:500;line-height:1.18">${heading}</h1>${paragraphs}${action}<div style="margin-top:26px;padding:16px 18px;border-radius:12px;background:#f3f5f8;color:#596474;font-size:13px;line-height:1.55"><strong style="color:#17202e">Private by design.</strong> Family Documents never asks you to reply with a password or verification code. If you were not expecting this message, you can safely ignore it.</div></td></tr><tr><td style="padding:22px 32px;border-top:1px solid #eceae4;color:#7a8290;font-size:12px;line-height:1.6">Sent by Family Documents · <a href="https://familydocuments.app" style="color:#5755c9">familydocuments.app</a><br>Need help? <a href="mailto:support@familydocuments.app" style="color:#5755c9">support@familydocuments.app</a></td></tr></table></td></tr></table></body></html>`;
}
