import test from "node:test";
import assert from "node:assert/strict";
import {createHash} from "node:crypto";
import {AuthorizationTransactionStore, ConnectorAuthority, ConnectorLifecycle, PROVIDERS, SelectionGrantStore} from "./connector-contract.mjs";

const redirect="https://app.example.test/oauth/google/callback";
const hash=value=>createHash("sha256").update(value).digest("base64url");
const verifyIdToken=(raw,expected)=>{if(!raw||raw.trustedVerifierResult!==true)throw new Error("invalid_signature");const c=raw.claims;if(c.issuer!==expected.issuer||c.audience!==expected.audience||hash(c.nonceClaim)!==expected.nonceHash)throw new Error("invalid_claims");return c};
const authStore=({clock=()=>1_000,ttlMs=300_000,allow=[redirect]}={})=>new AuthorizationTransactionStore({clock,ttlMs,redirectAllowList:{google_drive:Object.freeze(allow)},clients:{google_drive:"google-client-123"},verifyIdToken});
const token=(nonce,overrides={})=>({trustedVerifierResult:true,claims:{issuer:PROVIDERS.google_drive.issuer,audience:"google-client-123",subject:"provider-user",providerAccountId:"account-1",nonceClaim:nonce,...overrides}});

test("only narrow Google is executable and OneDrive is disabled",()=>{assert.equal(PROVIDERS.google_drive.liveAuthorization,true);assert.ok(PROVIDERS.google_drive.scopes.includes("https://www.googleapis.com/auth/drive.file"));assert.equal(PROVIDERS.one_drive.liveAuthorization,false);assert.deepEqual(PROVIDERS.one_drive.scopes,[])});
test("redirect policy rejects configured HTTP, userinfo and fragment",()=>{for(const value of ["http://app.example.test/cb","https://user@app.example.test/cb","https://app.example.test/cb#x"])assert.throws(()=>authStore({allow:[value]}),/unsafe_redirect_policy/);const store=authStore();for(const value of [`${redirect}/`,`${redirect}?x=1`,"https://evil.example/cb"])assert.throws(()=>store.issue({provider:"google_drive",sessionId:"s-1",redirectUri:value}),/redirect_not_allowed/)});
test("callback and trusted verifier bind signed identity claims",()=>{const store=authStore(),issued=store.issue({provider:"google_drive",sessionId:"s-1",redirectUri:redirect});const callback=store.consumeCallback({provider:"google_drive",sessionId:"s-1",redirectUri:redirect,state:issued.state,code:"code-1"});assert.throws(()=>store.verifyTokenExchange({exchangeHandle:callback.exchangeHandle,code:"code-1",rawIdToken:{trustedVerifierResult:false,claims:token(issued.nonce).claims}}),/invalid_signature/);assert.throws(()=>store.verifyTokenExchange({exchangeHandle:callback.exchangeHandle,code:"code-1",rawIdToken:token("invented")}),/invalid_claims/);const identity=store.verifyTokenExchange({exchangeHandle:callback.exchangeHandle,code:"code-1",rawIdToken:token(issued.nonce)});assert.equal(identity.providerSubject,"provider-user");assert.throws(()=>store.verifyTokenExchange({exchangeHandle:callback.exchangeHandle,code:"code-1",rawIdToken:token(issued.nonce)}),/invalid_or_expired_exchange/)});
test("callback is session bound, single use and inclusively expires",()=>{let now=1_000;const store=authStore({clock:()=>now,ttlMs:1_000}),issued=store.issue({provider:"google_drive",sessionId:"s-1",redirectUri:redirect});assert.throws(()=>store.consumeCallback({provider:"google_drive",sessionId:"other",redirectUri:redirect,state:issued.state,code:"c"}),/transaction_binding_mismatch/);now=2_000;assert.throws(()=>store.consumeCallback({provider:"google_drive",sessionId:"s-1",redirectUri:redirect,state:issued.state,code:"c"}),/invalid_or_expired_transaction/)});

const connector={id:"c-1",provider:"google_drive",ownerSubject:"owner-1",providerSubject:"provider-user",providerAccountId:"account-1",enabled:true,authorizationEpoch:1};
const pickerOutput=selectedAt=>({providerSubject:"provider-user",providerAccountId:"account-1",fileId:"file-1",fileVersion:"v7",mimeType:"application/pdf",selectedAt});
function selectionStore({clock=()=>10_000,ttlMs=2_000,observation={providerSubject:"provider-user",providerAccountId:"account-1",fileId:"file-1",fileVersion:"v7"},connectorRef=connector,observe}={}){return new SelectionGrantStore({clock,ttlMs,resolveConnector:id=>id==="c-1"?connectorRef:null,verifyPickerMessage:(raw,expected)=>{if(raw.origin!==expected.expectedOrigin||raw.sourceId!==expected.expectedSourceId||hash(raw.channelNonce)!==expected.channelNonceHash)throw new Error("unverified_picker_message");return raw.output},observeProviderFile:observe||(async()=>observation)})}
test("server-issued picker session rejects invented channel/source/origin and replay",()=>{const store=selectionStore(),session=store.issuePickerSession({ownerSubject:"owner-1",connectorId:"c-1",expectedOrigin:"https://drive.google.com",expectedSourceId:"window-1"}),base={session:session.session,ownerSubject:"owner-1",connectorId:"c-1"};for(const mutation of [{origin:"https://evil.example"},{sourceId:"window-2"},{channelNonce:"invented"}])assert.throws(()=>store.issueFromVerifiedPickerMessage({...base,rawMessage:{origin:"https://drive.google.com",sourceId:"window-1",channelNonce:session.channelNonce,output:pickerOutput(10_000),...mutation}}),/unverified_picker_message/);const grant=store.issueFromVerifiedPickerMessage({...base,rawMessage:{origin:"https://drive.google.com",sourceId:"window-1",channelNonce:session.channelNonce,output:pickerOutput(10_000)}});assert.ok(grant);assert.throws(()=>store.issueFromVerifiedPickerMessage({...base,rawMessage:{origin:"https://drive.google.com",sourceId:"window-1",channelNonce:session.channelNonce,output:pickerOutput(10_000)}}),/invalid_or_expired_picker_session/)});
test("selection redemption uses broker-owned observation and is owner/version bound",async()=>{const store=selectionStore(),session=store.issuePickerSession({ownerSubject:"owner-1",connectorId:"c-1",expectedOrigin:"https://drive.google.com",expectedSourceId:"window-1"}),grant=store.issueFromVerifiedPickerMessage({session:session.session,ownerSubject:"owner-1",connectorId:"c-1",rawMessage:{origin:"https://drive.google.com",sourceId:"window-1",channelNonce:session.channelNonce,output:pickerOutput(10_000)}});await assert.rejects(store.redeem({grant,ownerSubject:"wrong",connectorId:"c-1"}),/selection_binding_mismatch/);assert.equal((await store.redeem({grant,ownerSubject:"owner-1",connectorId:"c-1"})).fileVersion,"v7");await assert.rejects(store.redeem({grant,ownerSubject:"owner-1",connectorId:"c-1"}),/invalid_or_expired_selection_grant/);const mismatched=selectionStore({observation:{providerSubject:"provider-user",providerAccountId:"account-1",fileId:"file-1",fileVersion:"v8"}}),s=mismatched.issuePickerSession({ownerSubject:"owner-1",connectorId:"c-1",expectedOrigin:"https://drive.google.com",expectedSourceId:"window-1"}),g=mismatched.issueFromVerifiedPickerMessage({session:s.session,ownerSubject:"owner-1",connectorId:"c-1",rawMessage:{origin:"https://drive.google.com",sourceId:"window-1",channelNonce:s.channelNonce,output:pickerOutput(10_000)}});await assert.rejects(mismatched.redeem({grant:g,ownerSubject:"owner-1",connectorId:"c-1"}),/selection_binding_mismatch/)});
test("disconnect epoch invalidates an issued picker session before grant creation",()=>{const ref={...connector},store=selectionStore({connectorRef:ref}),session=store.issuePickerSession({ownerSubject:"owner-1",connectorId:"c-1",expectedOrigin:"https://drive.google.com",expectedSourceId:"window-1"});ref.enabled=false;ref.authorizationEpoch++;assert.throws(()=>store.issueFromVerifiedPickerMessage({session:session.session,ownerSubject:"owner-1",connectorId:"c-1",rawMessage:{origin:"https://drive.google.com",sourceId:"window-1",channelNonce:session.channelNonce,output:pickerOutput(10_000)}}),/connector_not_available/)});
test("disconnect epoch invalidates a grant before any broker call",async()=>{let calls=0;const ref={...connector},store=selectionStore({connectorRef:ref,observe:async()=>{calls++;return {providerSubject:"provider-user",providerAccountId:"account-1",fileId:"file-1",fileVersion:"v7"}}}),session=store.issuePickerSession({ownerSubject:"owner-1",connectorId:"c-1",expectedOrigin:"https://drive.google.com",expectedSourceId:"window-1"}),grant=store.issueFromVerifiedPickerMessage({session:session.session,ownerSubject:"owner-1",connectorId:"c-1",rawMessage:{origin:"https://drive.google.com",sourceId:"window-1",channelNonce:session.channelNonce,output:pickerOutput(10_000)}});ref.enabled=false;ref.authorizationEpoch++;await assert.rejects(store.redeem({grant,ownerSubject:"owner-1",connectorId:"c-1"}),/connector_not_available/);assert.equal(calls,0)});
test("disconnect during broker observation prevents redemption",async()=>{let release,started;const begun=new Promise(r=>started=r),wait=new Promise(r=>release=r),ref={...connector};const store=selectionStore({connectorRef:ref,observe:async()=>{started();await wait;return {providerSubject:"provider-user",providerAccountId:"account-1",fileId:"file-1",fileVersion:"v7"}}}),session=store.issuePickerSession({ownerSubject:"owner-1",connectorId:"c-1",expectedOrigin:"https://drive.google.com",expectedSourceId:"window-1"}),grant=store.issueFromVerifiedPickerMessage({session:session.session,ownerSubject:"owner-1",connectorId:"c-1",rawMessage:{origin:"https://drive.google.com",sourceId:"window-1",channelNonce:session.channelNonce,output:pickerOutput(10_000)}});const redeem=store.redeem({grant,ownerSubject:"owner-1",connectorId:"c-1"});await begun;ref.enabled=false;ref.authorizationEpoch++;release();await assert.rejects(redeem,/connector_not_available/)});

const connection={id:"c-1",provider:"google_drive",ownerSubject:"owner-1",providerSubject:"provider-user",providerAccountId:"account-1",tokenCiphertextRef:"vault-ref",version:1};
const lifecycleWith=revokeProvider=>new ConnectorLifecycle({revokeProvider,authority:new ConnectorAuthority()});
test("disconnect authorizes before idempotency lookup",async()=>{let release;const wait=new Promise(r=>release=r),lifecycle=new ConnectorLifecycle({revokeProvider:async()=>wait});lifecycle.add(connection);const owner=lifecycle.disconnect({id:"c-1",ownerSubject:"owner-1",operationId:"op-1",expectedVersion:1});await assert.rejects(lifecycle.disconnect({id:"c-1",ownerSubject:"wrong",operationId:"op-1",expectedVersion:1}),/connection_not_available/);release();assert.equal((await owner).revokeState,"revoked")});
test("concurrent disconnect is single-call, idempotent and local-disable-first",async()=>{let calls=0,disabled=false,release;const wait=new Promise(r=>release=r);let lifecycle;lifecycle=new ConnectorLifecycle({revokeProvider:async()=>{calls++;disabled=!lifecycle.canUse("c-1");await wait}});lifecycle.add(connection);const a=lifecycle.disconnect({id:"c-1",ownerSubject:"owner-1",operationId:"op-1",expectedVersion:1}),b=lifecycle.disconnect({id:"c-1",ownerSubject:"owner-1",operationId:"op-1",expectedVersion:1}),c=lifecycle.disconnect({id:"c-1",ownerSubject:"owner-1",operationId:"op-2",expectedVersion:1});release();const results=await Promise.all([a,b,c]);assert.equal(calls,1);assert.equal(disabled,true);assert.deepEqual(results[0],results[1]);assert.equal(results[2].localEnabled,false)});
test("failed provider revoke has an authorized idempotent retry",async()=>{let calls=0;const lifecycle=new ConnectorLifecycle({revokeProvider:async()=>{calls++;if(calls===1)throw new Error("offline")}});lifecycle.add(connection);const failed=await lifecycle.disconnect({id:"c-1",ownerSubject:"owner-1",operationId:"op-1",expectedVersion:1});assert.equal(failed.revokeState,"provider_revoke_retry_required");const retry=await lifecycle.disconnect({id:"c-1",ownerSubject:"owner-1",operationId:"op-2",expectedVersion:2});assert.equal(retry.revokeState,"revoked");assert.equal(calls,2);assert.equal(lifecycle.canUse("c-1"),false)});
test("duplicate IDs and stale operations fail closed",async()=>{const lifecycle=new ConnectorLifecycle({revokeProvider:async()=>{}});lifecycle.add(connection);assert.throws(()=>lifecycle.add(connection),/duplicate_connection_id/);await assert.rejects(lifecycle.disconnect({id:"c-1",ownerSubject:"owner-1",operationId:"op-x",expectedVersion:2}),/stale_connection_version/)});
test("real lifecycle disconnect invalidates stale grants before broker access",async()=>{let brokerCalls=0;const authority=new ConnectorAuthority(),lifecycle=new ConnectorLifecycle({authority,revokeProvider:async()=>{}});lifecycle.add(connection);const store=new SelectionGrantStore({resolveConnector:id=>authority.get(id),verifyPickerMessage:(raw,expected)=>{if(raw.origin!==expected.expectedOrigin||raw.sourceId!==expected.expectedSourceId||hash(raw.channelNonce)!==expected.channelNonceHash)throw new Error("unverified_picker_message");return raw.output},observeProviderFile:async()=>{brokerCalls++;return {providerSubject:"provider-user",providerAccountId:"account-1",fileId:"file-1",fileVersion:"v7"}}});const picker=store.issuePickerSession({ownerSubject:"owner-1",connectorId:"c-1",expectedOrigin:"https://drive.google.com",expectedSourceId:"window-1"}),grant=store.issueFromVerifiedPickerMessage({session:picker.session,ownerSubject:"owner-1",connectorId:"c-1",rawMessage:{origin:"https://drive.google.com",sourceId:"window-1",channelNonce:picker.channelNonce,output:pickerOutput(Date.now())}});await lifecycle.disconnect({id:"c-1",ownerSubject:"owner-1",operationId:"op-real",expectedVersion:1});await assert.rejects(store.redeem({grant,ownerSubject:"owner-1",connectorId:"c-1"}),/connector_not_available/);assert.equal(brokerCalls,0)});
test("reconnect uses a new non-reusable generation",async()=>{let brokerCalls=0;const authority=new ConnectorAuthority(),lifecycle=new ConnectorLifecycle({authority,revokeProvider:async()=>{}});lifecycle.add(connection);const store=new SelectionGrantStore({resolveConnector:id=>authority.get(id),verifyPickerMessage:(raw,expected)=>{if(hash(raw.channelNonce)!==expected.channelNonceHash)throw new Error("unverified_picker_message");return raw.output},observeProviderFile:async()=>{brokerCalls++;return {providerSubject:"provider-user",providerAccountId:"account-1",fileId:"file-1",fileVersion:"v7"}}}),picker=store.issuePickerSession({ownerSubject:"owner-1",connectorId:"c-1",expectedOrigin:"https://drive.google.com",expectedSourceId:"window-1"}),grant=store.issueFromVerifiedPickerMessage({session:picker.session,ownerSubject:"owner-1",connectorId:"c-1",rawMessage:{origin:"https://drive.google.com",sourceId:"window-1",channelNonce:picker.channelNonce,output:pickerOutput(Date.now())}});await lifecycle.disconnect({id:"c-1",ownerSubject:"owner-1",operationId:"op-real",expectedVersion:1});lifecycle.add({...connection,version:3});assert.ok(authority.get("c-1").authorizationEpoch>1);await assert.rejects(store.redeem({grant,ownerSubject:"owner-1",connectorId:"c-1"}),/connector_not_available/);assert.equal(brokerCalls,0)});
test("reconnect may safely reuse an operation ID without receiving stale receipt",async()=>{let revokes=0;const authority=new ConnectorAuthority(),lifecycle=new ConnectorLifecycle({authority,revokeProvider:async()=>{revokes++}});lifecycle.add(connection);const first=await lifecycle.disconnect({id:"c-1",ownerSubject:"owner-1",operationId:"same-op",expectedVersion:1});lifecycle.add({...connection,version:3});assert.equal(lifecycle.canUse("c-1"),true);const second=await lifecycle.disconnect({id:"c-1",ownerSubject:"owner-1",operationId:"same-op",expectedVersion:3});assert.equal(revokes,2);assert.notEqual(first.authorizationEpoch,second.authorizationEpoch);assert.equal(second.revokeState,"revoked");assert.equal(lifecycle.canUse("c-1"),false)});
