import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {createRequire} from "node:module";
const require=createRequire(import.meta.url);
const {PrototypeAdapter,buildSearchView,restoreInvoker,stateCopy}=require("./model.js");
const html=readFileSync(new URL("index.html",import.meta.url),"utf8"),css=readFileSync(new URL("styles.css",import.meta.url),"utf8"),js=readFileSync(new URL("app.js",import.meta.url),"utf8"),model=readFileSync(new URL("model.js",import.meta.url),"utf8");
for(const route of ["auth","home","review","records","search","add","connections","household"])assert.match(js,new RegExp(`function ${route}\\(`),`missing ${route} screen`);
for(const scenario of ["loading","empty","error","restricted","offline","conflict","stale"])assert.match(html,new RegExp(`value="${scenario}"`),`missing ${scenario} scenario`);
for(const hook of ["Skip to main content","aria-label=\"Primary navigation\"","aria-live=\"polite\"","<dialog"])assert.ok(html.includes(hook),`missing accessibility hook: ${hook}`);
assert.doesNotMatch(html,/id="screen"[^>]*aria-live/,"whole screen must not be a live region");
assert.match(css,/@media\(max-width:760px\)/);assert.match(css,/@media\(forced-colors:active\)/);assert.match(css,/@media\(prefers-reduced-motion:reduce\)/);assert.match(css,/:focus-visible/);
const adapter=new PrototypeAdapter();
const connectors=adapter.getConnectors();assert.deepEqual(connectors.map(x=>x.id),["google-drive","one-drive"]);assert.equal(connectors[0].scope,"drive.file");assert.match(connectors[1].picker,/OneDrive/);
const insurance=adapter.search("When does our house insurance renew?");assert.equal(insurance.kind,"results");assert.equal(insurance.results[0].id,"tower-policy");assert.match(insurance.results[0].citation,/page 1/);
const wof=adapter.search("Toyota WOF due?");assert.equal(wof.kind,"results");assert.equal(wof.results[0].id,"toyota-wof");
const both=adapter.search("insurance and WOF");assert.equal(both.results.length,2);
const towerView=buildSearchView(both,"tower-policy"),toyotaView=buildSearchView(both,"toyota-wof");
assert.equal(towerView.selectedSource.id,"tower-policy");assert.match(towerView.selectedSource.citation,/Tower-policy/);
assert.equal(toyotaView.selectedSource.id,"toyota-wof");assert.match(toyotaView.selectedSource.citation,/Toyota-WOF/);
assert.equal(buildSearchView(both,"not-authorised").selectedSource,null,"unknown source ID must fail closed");
let firstFocused=0,secondFocused=0;
const firstDuplicate={dataset:{openSource:"tower-policy"},isConnected:true,focus(){firstFocused++}},secondDuplicate={dataset:{openSource:"tower-policy"},isConnected:true,focus(){secondFocused++}};
assert.equal(firstDuplicate.dataset.openSource,secondDuplicate.dataset.openSource,"fixture must model duplicated source IDs");
assert.equal(restoreInvoker(secondDuplicate),true);assert.equal(secondFocused,1,"actual second invoker must regain focus");assert.equal(firstFocused,0,"same-ID first control must not receive focus");
assert.equal(restoreInvoker({isConnected:false,focus(){throw new Error("must not focus detached control")}}),false);
const conflict=adapter.search("insurance and WOF conflict");const conflictView=buildSearchView(conflict);
assert.equal(conflictView.kind,"conflict");assert.equal(conflictView.sources.length,2);assert.match(conflictView.headline,/compare/i);
const unsupported=adapter.search("Where is a missing passport?");assert.equal(unsupported.kind,"abstain");assert.equal(unsupported.results.length,0);assert.equal(adapter.search("").kind,"prompt");
assert.equal(adapter.search("Where is our home?").kind,"abstain","a generic home mention must not produce an insurance answer");
const first=adapter.getHousehold();first.name="changed";assert.equal(adapter.getHousehold().name,"Harbour household","adapter returns isolated synthetic copies");
for(const route of ["home","review","records","search","add"])for(const scenario of ["loading","empty","error","restricted","offline","conflict","stale"]){const copy=stateCopy(route,scenario,{query:"saved question"});assert.equal(copy.length,2);assert.ok(copy.every(Boolean),`${route}/${scenario} missing route-specific recovery copy`)}
assert.match(js,/Live sign-in remains disabled/);assert.match(js,/data-connector-preview/);assert.match(html,/data-route-button="connections"/);
assert.match(js,/Continue with Google/);assert.match(js,/Create account with email/);assert.match(js,/Preview only — credentials are not sent or saved/);assert.match(js,/data-invite-form/);assert.match(js,/Default deny/);assert.match(js,/data-category-form/);assert.match(js,/never become facts silently/i);
assert.match(js,/data-state-help/);assert.match(js,/openHelp\(e\.currentTarget\)/,"restricted Help must open contextual dialog");assert.match(js,/render\(\{tabFocus:true\}\)/,"tab activation must restore focus");assert.match(js,/data-home-action/);assert.match(js,/data-record/);assert.match(js,/data-open-source/);
assert.match(js,/if\(view\.kind==="conflict"\)/,"search renderer must explicitly handle adapter conflicts");assert.match(js,/state\.sourceInvoker=invoker/,"source controls must retain their actual invoking element");assert.match(js,/restoreInvoker\(prior\)/,"source close must restore the actual retained invoker");
assert.ok(js.indexOf('class="text-button skip-action"')<js.indexOf('class="secondary-button reject-action"'),"mobile Review DOM order must be Confirm, Skip, Not correct");
for(const source of [html,css,js,model])for(const forbidden of [/fetch\s*\(/,/XMLHttpRequest/,/localStorage/,/sessionStorage/,/indexedDB/,/WebSocket/,/EventSource/])assert.doesNotMatch(source,forbidden,`forbidden runtime capability: ${forbidden}`);
assert.doesNotMatch(html,/<script[^>]+src=["']https?:/i);assert.doesNotMatch(css,/@import|url\s*\(/i);
console.log("PASS: prototype model, state recovery, action wiring and static safety checks");
